### ISSUE TITLE
不维护了么，直接报错了

### ISSUE THREAD

**Issue by wu529778790** [helloworld-Co/html2md#30]
{
  "code": 0,
  "msg": "程序异常了~"
}

#### Other relevant information（格外信息）
- Your OS:
- Your broswer version:

**Comment by hsl947** [comment]
这个报错跟html2md无关，是对方网站不支持抓取了。你可以提供一下报错的网址。

**Comment by JosonJiang** [comment]
`index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at PluginPass.Program (C:\工作目录\近期工作\Docsify\html2md\node_modules\@nuxt\babel-preset-app\src\polyfills-plugin.js:15:34)
    at newFn (C:\工作目录\近期工作\Docsify\html2md\node_modules\@babel\traverse\lib\visitors.js:149:21)
    at NodePath._call (C:\工作目录\近期工作\Docsify\html2md\node_modules\@babel\traverse\lib\path\context.js:45:20)
    at NodePath.call (C:\工作目录\近期工作\Docsify\html2md\node_modules\@babel\traverse\lib\path\context.js:35:17)
    at NodePath.visit (C:\工作目录\近期工作\Docsify\html2md\node_modules\@babel\traverse\lib\path\context.js:80:31)
    at TraversalContext.visitQueue (C:\工作目录\近期工作\Docsify\html2md\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\工作目录\近期工作\Docsify\html2md\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\工作目录\近期工作\Docsify\html2md\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\工作目录\近期工作\Docsify\html2md\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at traverse (C:\工作目录\近期工作\Docsify\html2md\node_modules\@babel\traverse\lib\index.js:49:34)
    at transformFile (C:\工作目录\近期工作\Docsify\html2md\node_modules\@nuxt\webpack\node_modules\@babel\core\lib\transformation\index.js:81:29)
    at transformFile.next (<anonymous>)
    at run (C:\工作目录\近期工作\Docsify\html2md\node_modules\@nuxt\webpack\node_modules\@babel\core\lib\transformation\index.js:24:12)
    at run.next (<anonymous>)
    at transform (C:\工作目录\近期工作\Docsify\html2md\node_modules\@nuxt\webpack\node_modules\@babel\core\lib\transform.js:22:41)
    at transform.next (<anonymous>)
    at step (C:\工作目录\近期工作\Docsify\html2md\node_modules\gensync\index.js:261:32)
    at C:\工作目录\近期工作\Docsify\html2md\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\工作目录\近期工作\Docsify\html2md\node_modules\gensync\index.js:223:11)
    at C:\工作目录\近期工作\Docsify\html2md\node_modules\gensync\index.js:189:28
    at C:\工作目录\近期工作\Docsify\html2md\node_modules\@nuxt\webpack\node_modules\@babel\core\lib\gensync-utils\async.js:68:7
    at C:\工作目录\近期工作\Docsify\html2md\node_modules\gensync\index.js:113:33
    at step (C:\工作目录\近期工作\Docsify\html2md\node_modules\gensync\index.js:287:14)
    at C:\工作目录\近期工作\Docsify\html2md\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\工作目录\近期工作\Docsify\html2md\node_modules\gensync\index.js:223:11)
                                                                                              friendly-errors 10:03:27
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
                                                                                              friendly-errors 10:03:27

× Client
  Compiled with some errors in 16.60s

√ Server
  Compiled successfully in 43.59s

i Waiting for file changes                                                                                    10:03:54

 READY  Server listening on http://localhost:3031`

**Comment by hsl947** [comment]
> `index.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15) at Function.Module._load (internal/modules/cjs/loader.js:746:27) at Module.require (internal/modules/cjs/loader.js:974:19) at require (internal/modules/cjs/helpers.js:93:18) friendly-errors 10:03:27 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js friendly-errors 10:03:27
> 
> × Client Compiled with some errors in 16.60s
> 
> √ Server Compiled successfully in 43.59s
> 
> i Waiting for file changes 10:03:54
> 
> READY Server listening on [http://localhost:3031`](http://localhost:3031%60)

node版本多少，建议12
